name: ${name}
version: ${version}
main: ${group}.${name}
api-version: '1.21'
description: Плагин для игнорирования мобов
author: FlyAwayMaking
website: https://github.com/flyawaymaking

commands:
  mobignore:
    description: Основная команда
    usage: /<command> [reload]

permissions:
  mobignore.use:
    description: Разрешает использовать команду mobignore
    default: op
  mobignore.reload:
    description: Разрешает использовать команду reload
    default: op
